### ISSUE TITLE
build fails with test errors

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#148]
synced with bab7910 
```
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.searchcode.app.util.OWASPFileClassifierResultTest
Running com.searchcode.app.util.SearchcodeLibTest
Tests run: 51, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 1.485 sec <<< FAILURE! - in com.searchcode.app.util.SearchcodeLibTest
testIsBinaryEdge3(com.searchcode.app.util.SearchcodeLibTest)  Time elapsed: 0.014 sec  <<< FAILURE!
junit.framework.AssertionFailedError
        at com.searchcode.app.util.SearchcodeLibTest.testIsBinaryEdge3(SearchcodeLibTest.java:205)

testIsBinaryFalse(com.searchcode.app.util.SearchcodeLibTest)  Time elapsed: 0.005 sec  <<< FAILURE!
junit.framework.AssertionFailedError
        at com.searchcode.app.util.SearchcodeLibTest.testIsBinaryFalse(SearchcodeLibTest.java:97)

testIsBinary(com.searchcode.app.util.SearchcodeLibTest)  Time elapsed: 0.004 sec  <<< FAILURE!
junit.framework.AssertionFailedError
        at com.searchcode.app.util.SearchcodeLibTest.testIsBinary(SearchcodeLibTest.java:75)

Running com.searchcode.app.util.SpellingCorrectorTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.279 sec - in com.searchcode.app.util.SpellingCorrectorTest Running com.searchcode.app.util.UniqueRepoQueueTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.searchcode.app.util.UniqueRepoQueueTest

Results :

Failed tests:
  SearchcodeLibTest.testIsBinary:75
  SearchcodeLibTest.testIsBinaryEdge3:205
  SearchcodeLibTest.testIsBinaryFalse:97

Tests run: 328, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by boyter** [comment]
Issue was some bad tests. Refactored slightly.
