### ISSUE TITLE
Errors to Resolve

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#42]
15:57:41.902 kubtst1-scalyrnetes-4oogs [DefaultQuartzScheduler_Worker-8] ERROR org.quartz.core.JobRunShell - Job DEFAULT.updateindex-file-0 threw an unhandled Exception:  
15:57:41.902 kubtst1-scalyrnetes-4oogs java.util.NoSuchElementException  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at java.util.ArrayDeque.remove(ArrayDeque.java:447)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:105)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at com.searchcode.app.util.LoggerWrapper.info(LoggerWrapper.java:99)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at com.searchcode.app.jobs.IndexFileRepoJob.execute(IndexFileRepoJob.java:73)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)  
15:57:41.902 kubtst1-scalyrnetes-4oogs 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

Fix the above exceptions.

**Comment by boyter** [comment]
Resolved https://github.com/boyter/searchcode-server/commit/9adfe55acaf14e472bf8ebce599cb8628f27bc0a
